server:
  servlet:
    context-path: /ape
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/ape
    username: root
    password: 910103zyx
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.blue.ape.entity
